# set environment variables here and figaro will do the rest
AMAZON_ACCESS_KEY_ID: ''
AMAZON_SECRET_ACCESS_KEY: ''
FACEBOOK_APP_ID: ''
GOOGLE_MAPS_API_KEY: ''
SECRET_KEY_BASE: ''
SENDGRID_PASSWORD: ''
SENDGRID_USERNAME: ''
TWITTER_ACCESS_TOKEN: ''
TWITTER_ACCESS_SECRET: ''
TWITTER_CONSUMER_KEY: ''
TWITTER_CONSUMER_SECRET: ''
