development:
  clients:
    default:
      database: novels
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true

test:
  clients:
    default:
      database: novels_on_location_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        raise_not_found_error: false
        retry_interval: 0

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
  options:
    raise_not_found_error: false
    use_activesupport_time_zone: true
