defaults: &defaults
  options:
    raise_not_found_error: true

development:
  <<: *defaults
  clients:
    default:
      database: novels
      hosts:
        - <%= Rails.application.config.main_host %>:27017

test:
  <<: *defaults
  clients:
    default:
      database: novels_on_location_test
      hosts:
        - <%= Rails.application.config.main_host %>:27017

production:
  <<: *defaults
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
