defaults: &defaults
  allow_dynamic_fields: false

development:
  <<: *defaults
  database: novels
  host: localhost

test:
  <<: *defaults
  database: novels_test
  host: localhost

production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>