name: Test
on:
  push:
permissions: read-all
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - uses: supercharge/mongodb-github-action@5a87bd81f88e2a8b195f8b7b656f5cda1350815a
      with:
        mongodb-version: 8.0
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f
      with:
        ruby-version: 4.0.3
        bundler-cache: true
    - run: bundle exec rspec spec/features/browsing_locations_spec.rb:19
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    - run: bundle exec rubocop
    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
      if: failure()
      with:
        name: capybara-screenshots
        path: tmp/capybara/*.png
        if-no-files-found: ignore
#     - run: bundle exec inch --pedantic
#     - uses: aktions/codeclimate-test-reporter@7634aa9ac7883182f583f15ff7b6ff519939dd0a
#       with:
#         codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
#         command: after-build --coverage-input-type lcov
#     - uses: coverallsapp/github-action@cfd0633edbd2411b532b808ba7a8b5e04f76d2c8
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}
