name: Test
on:
  push:
permissions: read-all
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - uses: supercharge/mongodb-github-action@5a87bd81f88e2a8b195f8b7b656f5cda1350815a
      with:
        mongodb-version: 8.0
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f
      with:
        ruby-version: 4.0.3
        bundler-cache: true
    - run: bundle exec rspec
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    - run: bundle exec rubocop
    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
      with:
        name: coverage
        path: coverage/
        if-no-files-found: ignore
    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
      if: failure()
      with:
        name: screenshots
        path: tmp/capybara/*.png
        if-no-files-found: ignore
#     - run: bundle exec inch --pedantic
    - uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637 # v2.3.0
      with:
        oidc: true
        files: coverage/lcov.info
    - uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
